### PR TITLE
Add UDP support.

### PR DESCRIPTION
**Pull request by jedsmallwood**
Merely updating the package.json and running 'npm update' got everything squared away.  I was able to run the collector, evaluator and random emitter to see that all of the components were functioning.

On a side note, it appears that the README.md states that websocket-client is used when in fact it is just websocket.  I think these are two different projects.

### CODE REVIEW

**Comment by mbostock** [comment]
Thanks, yes, the README is out-of-date from when we switched WebSocket implementations.

**Comment by mbostock** [comment]
Retitled this pull request, as the latest release 0.0.13 upgrades the websocket dependency and thus adds support for Node 0.6.x.

**Comment by jedsmallwood** [comment]
Sounds good.  This is my first time using git so I think I should have just made a new branch or something to do this other stuff.

**Comment by jedsmallwood** [comment]
I'm going to clean this up a bit, just do the UDP and then do the cluster as a different pull.

**Pull request closed without merging**
