### PR TITLE
Add http emitter

### PR DESCRIPTION
**Pull request by trotter**
I added an http emitter incase for cases where the cube server cannot be accessed via websockets or udp.

### CODE REVIEW

**Comment by mbostock** [comment]
I like it.

I think it could be further improved by ensuring only one POST request at-a-time, which is to say, the next request should not be kicked off until the response is received from the server. If there's an error, or the status code is not 200, then you'd want to push the event back onto the queue for retry.

To reduce overhead, each POST should send an array of events, rather than just a single event. For example, you could send every queued event since the last POST. Though, you'd likely want to limit the number of events per POST to a reasonable amount (say, 500); you probably don't want to post tens of thousands of events in a single request.

I'd also be tempted to use a setTimeout rather than process.nextTick when using POST, so that we don't DOS the collector. If you can post 500 events in a single request, then a timeout of 500 ms would mean 1,000 events per second at 2 requests per second which I think is more than reasonable.

**Comment by trotter** [comment]
Thanks for the feedback. I'll try to find time tonight to make these changes.

**Comment by trotter** [comment]
I've updated this pull request with what I think are fixes to the requested changes. Let me know what you think.

**Comment by mbostock** [comment]
Right on, that looks good. Sorry to ask the obvious, but have you had a chance to test it locally, too?

**Comment by mbostock** [comment]
And, could I please ask you to sign the [CLI](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1)? I know, it's annoying, but it's required. :hammer:

**Comment by trotter** [comment]
Yup, I've tested it locally using the random emitter example. 2880
events were created in Mongo. As for the CLI, I just signed it. Let me
know if I need to do anything else.

**Comment by mbostock** [comment]
Looks good!

**Pull request merged**
