### PR TITLE
Use ObjectID timestamps instead of dedicated field

### PR DESCRIPTION
**Pull request by Marsup**
Hello Mike,

This is my attempt to solve issue #16. Tests are good on my side except `test.js` which was already failing.
I've followed your will to keep the `id` in `d` with a sparse unique index.

I haven't run any performance comparison but I'd be interested to know if you give it a shot.

### CODE REVIEW

**Comment by mbostock** [comment]
Does this mean you can't send two events with the same type and time?

**Comment by Marsup** [comment]
If you are referring to @temsa comment, the computation of ObjectID by the mongodb module is split like this :
- timestamp : now taken from the event time
- machine : randomized at the node module startup
- pid : taken from the node pid
- increment : incremented at the module level each time a new ObjectID is created (with a modulo to always fit on 24 bits)

I think collisions are nearly impossible with this logic, even on multi-process/machine scenarios.

**Comment by mbostock** [comment]
Cool, thanks for the clarification.

**Comment by temsa** [comment]
@Marsup ain't it missing some code for managing data collection, e.g. through collectd ?

**Comment by Marsup** [comment]
The `collectd` putter is reusing the `event` putter, so it shouldn't matter which source you are using as long as you let `event` handle it.

**Comment by temsa** [comment]
@Marsup just did not seen the [id creation](/Marsup/cube/commit/12f704c525e28d452586f81b00587bf1ac4f31af#L0R39) in the commit diff

**Comment by Marsup** [comment]
I have just seen a slight anomaly in this PR, on the line 196 of event.js.
Since _id will now always be an ObjectID, you will never get any, but you still get your custom id in the data field.
What do you prefer @mbostock, duplicating the id in both data and id, or simply removing the id field ?

**Comment by sahil107** [comment]
Marsup:objectid-timestamps

**Pull request closed without merging**
