### PR TITLE
Allowing mongodb authentication

### PR DESCRIPTION
**Pull request by mrkurt**
This change will authenticate with the mongodb server if a username and password are provided in the config.

### CODE REVIEW

**Comment by mbostock** [comment]
Hooray!

**Comment by mbostock** [comment]
Hi @mrkurt, would you mind signing the [cla](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) so I can merge this request? Thanks!

**Comment by mrkurt** [comment]
Done!

**Comment by mbostock** [comment]
Merged into #40 for 0.2.0 staging.

**Pull request closed without merging**
